config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "employees#index"
  resources :employees
  resources :main_menu, only: [:index]
  resources :useless, only: [:index]
  resources :sessions, only: [:create, :destroy]
  resources :products, :path => "productListing" do
    get :search, on: :collection
  end

  resources :cart, only: [:addItem, :subItem, :deleteItem, :deleteAllItems, :index] do
    get :addItem, on: :collection
    get :subItem, on: :collection
    get :deleteItem, on: :collection
    get :deleteAllItems, on: :collection
  end

  resources :transaction, only: [:product_browsing, :productSearch, :index, :show, :create, :destroy] do
    get :productSearch, on: :collection
    get :product_browsing, on: :collection
  end
end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  before_action :checkEmployee

  def index
    employee = Employee.find_by(employeeId: session[:employeeId])
    @transactions = employee.transactions
  end

  def show
    employee = Employee.find_by(employeeId: session[:employeeId])
    @transaction = employee.transactions.find_by(id: params[:id])
  end

  def create
    employee = Employee.find_by(employeeId: session[:employeeId])
    cart = employee.cart
    newTrans = Transaction.new
    newTrans.employee = employee
    save = newTrans.setTrans(cart.getCart)
    if save
      flash[:notice] = "Product created"
      redirect_to transaction_index_path
      cart.setCart({})
    else
      flash[:error] = "Product did not save, please try again"
      redirect_to cart_index_path
    end
  end

  def destroy
    transaction_id = params[:id]
    employee = Employee.find_by(employeeId: session[:employeeId])
    transaction = employee.transactions.find_by(id: transaction_id)

    if transaction.destroy
      flash[:notice] = "Transaction was deleted"
    else
      flash[:error] = "Transaction was not deleted, please try again"
    end
    redirect_to transaction_index_path
  end

  def product_browsing
    @products = Product.all
  end

  def productSearch
    searchCriteria = params[:searchCriteria]
    allProducts = Product.all
    @products = []

    if searchCriteria.nil?
      render plain: "Search Criteria is nil"
      return
    end
    if allProducts.empty?
      return
    end

    allProducts.each do |product|
      match = true
      lookupCode = product.lookupCode
      count = 0
      searchCriteria.split("").each { |c|
        lookupCodeCharacter = lookupCode[count]
        if lookupCodeCharacter.nil?
          match = false
        end
        match = false unless c == lookupCodeCharacter
        count = count + 1
      }
      if match
        @products.append(product)
      end
      puts "Criteria: #{searchCriteria}"
      puts "Product LookupCode: #{lookupCode}"
      puts "Match: #{match}"
    end
    render "product_browsing.html.erb"
  end

  def checkEmployee
    if Employee.find_by(employeeId: session[:employeeId]).nil?
      render plain: "Can't find employeeId"
      return
    end
  end
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/transaction/index.html.erb
<%= button_to "Main Menu", main_menu_index_path, method: :get %>
<%= button_to "Create New Transaction", product_browsing_transaction_index_path, method: :get %>

<% @transactions.each do |transaction| %>
  Total Items: <%= transaction.total %>
  <br>
  Total Unique Items: <%= transaction.productCount %>
  <br>
  Total Price: <%= transaction.totalPrice %>
  <br>
  <%= button_to "Show", transaction_path(transaction.id), method: :get %>
  -------------------------------------------------------
  <br>

<% end %>

app/views/transaction/product_browsing.html.erb
<%= button_to "Main Menu", main_menu_index_path, method: :get %>
<%= button_to "Cart", cart_index_path, method: :get %>
<br>
<%= form_with(url: productSearch_transaction_index_path, method: "get", local: true) do %>
  <%= label_tag(:searchCriteria, "search for:") %>
  <%= text_field_tag(:searchCriteria) %>
  <%= submit_tag("search") %>
<% end %>
<br>

<% @products.each do |product| %>
  LookupCode: <%= product.lookupCode %> <br>
  Price: <%= product.price %> <br> 
  <%= button_to "Add To Cart", addItem_cart_index_path(lookupCode: product.lookupCode), params: { lookupCode: product.lookupCode, original: "productAdd" }, method: :get, action: :addItem %>
  ----------------------------- 
  <br>
<% end %>

<% # <%= button_to "go to cart", cart_index_path, method: :get %>
<%= button_to "Transaction Summary", transaction_index_path, method: :post %>

app/views/transaction/show.html.erb
<%= button_to "Main Menu", main_menu_index_path, method: :get %>

Products: 
<br>
<br>
<% @transaction.getTrans().each do |key, value| %>
  LookupCode: <%= key %>
  <br>
  Price: <%= Product.find_by(lookupCode: key).price %>
  <br>
  Quantity: <%= value %>
  <br>
----------------------------------------
  <br>

<% end %>
<br>
Total Items: <%= @transaction.total %>
<br>
Total Unique Items: <%= @transaction.productCount %>
<br>
Total Price: <%= @transaction.totalPrice %>
<br>

<%= button_to "Delete Transaction", transaction_path(@transaction.id), method: :delete %>