config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "employees#index"
  resources :employees
  resources :main_menu, only: [:index]
  resources :useless, only: [:index]
  resources :sessions, only: [:create, :destroy]
  resources :products, :path => "productListing" do
    get :search, on: :collection
  end

  resources :cart, only: [:addItem, :subItem, :deleteItem, :deleteAllItems, :index] do
    get :addItem, on: :collection
    get :subItem, on: :collection
    get :deleteItem, on: :collection
    get :deleteAllItems, on: :collection
  end

  resources :transaction, only: [:product_browsing, :productSearch, :index, :show, :create, :destroy] do
    get :productSearch, on: :collection
    get :product_browsing, on: :collection
  end
end

app/controllers/main_menu_controller.rb
class MainMenuController < ApplicationController
  def index
    @employee = Employee.find_by(employeeId: session[:employeeId])
  end
end

app/helpers/main_menu_helper.rb
module MainMenuHelper
end

app/views/main_menu/index.html.erb
<h1> Main Menu </h1>
<%= link_to "Sign Out", session_path(session[:employeeId]), method: :delete %>
<br>
<br>

<%= button_to "Transactions", transaction_index_path, method: :get %>
<%= button_to "Products", products_path, method: :get %>
<% if @employee.isElevatedUser == true %>
  <%= button_to new_employee_path, class: "button", :method => "get" do %>Create Employee<% end %>
  <%= button_to "Sales Report", useless_index_path, method: :get %>
  <%= button_to "Cashier Report", useless_index_path, method: :get %>
<% end %>