config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "employees#index"
  resources :employees
  resources :main_menu, only: [:index]
  resources :useless, only: [:index]
  resources :sessions, only: [:create, :destroy]
  resources :products, :path => "productListing" do
    get :search, on: :collection
  end

  resources :cart, only: [:addItem, :subItem, :deleteItem, :deleteAllItems, :index] do
    get :addItem, on: :collection
    get :subItem, on: :collection
    get :deleteItem, on: :collection
    get :deleteAllItems, on: :collection
  end

  resources :transaction, only: [:product_browsing, :productSearch, :index, :show, :create, :destroy] do
    get :productSearch, on: :collection
    get :product_browsing, on: :collection
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :lookupCode, presence: true, uniqueness: true

  before_validation :lowerCase, on: :create

  private

  def lowerCase
    self.lookupCode = lookupCode.downcase
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def search
    searchCriteria = params[:searchCriteria]
    allProducts = Product.all
    @products = []

    if searchCriteria.nil?
      render plain: "Search Criteria is nil"
      return
    end
    if allProducts.empty?
      return
    end

    allProducts.each do |product|
      match = true
      lookupCode = product.lookupCode
      count = 0
      searchCriteria.split("").each { |c|
        lookupCodeCharacter = lookupCode[count]
        if lookupCodeCharacter.nil?
          match = false
        end
        match = false unless c == lookupCodeCharacter
        count = count + 1
      }
      if match
        @products.append(product)
      end
      puts "Criteria: #{searchCriteria}"
      puts "Product LookupCode: #{lookupCode}"
      puts "Match: #{match}"
    end
    render "index.html.erb"
  end

  def show
    @product = Product.find_by(lookupCode: params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    id = params[:product][:id]
    count = params[:product][:count]
    price = params[:product][:price]

    product = Product.find_by(lookupCode: id)
    if not product.nil?
      flash[:error] = "Product already exists"
      redirect_to new_product_path
      return
    end

    product = Product.new(lookupCode: id, count: count, price: price)

    if product.save
      flash[:notice] = "Product created"
      redirect_to edit_product_path(id)
    else
      flash[:error] = "Product did not save, please try again"
      redirect_to new_product_path
    end
  end

  def edit
    @product = Product.find_by(lookupCode: params[:id])
  end

  def update
    lookupCode = params[:product][:lookupCode]
    count = params[:product][:count]
    price = params[:product][:price]

    product = Product.find_by(lookupCode: lookupCode)
    product.count = count
    product.price = price

    if product.save
      flash[:notice] = "Product was successfully saved"
    else
      flash[:error] = "Product was not saved, please try again"
    end
    redirect_to edit_product_path(lookupCode)
  end

  def destroy
    lookupCode = params[:id]

    product = Product.find_by(lookupCode: lookupCode)

    if product.destroy
      flash[:notice] = "Product was deleted"
      carts = Cart.all
      carts.each do |cart|
        hash = cart.getCart()
        hash = hash.reject { |k, v| k == lookupCode }
        cart.setCart(hash)
      end
    else
      flash[:error] = "Product was not deleted, please try again"
    end
    redirect_to products_path
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<%= button_to "Main Menu", main_menu_index_path, method: :get %>
<%= button_to "Product Listing", products_path, method: :get %>
<br>
<%= form_with model: @product, method: "put" do |f| %>
    <%= f.label :lookupCode, "LookupCode" %>
    <%= f.text_field :lookupCode, readonly: true %><br>
    <%= f.label :price, "Price" %>
    <%= f.text_field :price, :required => true %> <br>
    <%= f.label :count, "Count" %>
    <%= f.text_field :count, :required => true %><br>
    <%= f.submit "Edit" %>
<% end %>
<%= button_to "Delete", product_path, method: :delete %>

app/views/products/index.html.erb
<%= button_to "Main Menu", main_menu_index_path, method: :get %>
<%= button_to "Create New", new_product_path, method: :get %>
<br>
<%= form_with(url: "/productListing/search", method: "get", local: true) do %>
  <%= label_tag(:searchCriteria, "search for:") %>
  <%= text_field_tag(:searchCriteria) %>
  <%= submit_tag("search") %>
<% end %>
<br>
<% @products.each do |product| %>
  LookupCode: <%= product.lookupCode %> <br>
  Price: <%= product.price %> <br>
  <%= button_to "show", product_path(product.lookupCode), method: :get %>
  ------------------------
  <br>
<% end %>

app/views/products/new.html.erb
<%= button_to "Main Menu", main_menu_index_path, method: :get %>
<br>
<%= form_with model: @product do |f| %>
    <%= f.label :id, "Look-UP Code" %>
    <%= f.text_field :id, :required => true %><br>
    <%= f.label :price, "Price" %>
    <%= f.text_field :price, :required => true %> <br>
    <%= f.label :count, "Count" %>
    <%= f.text_field :count, :required => true %><br>
    <%= f.submit "Create" %>
<% end %>

app/views/products/search.html.erb
<%= button_to "ProductListing", products_path, method: :get %>
<% @products.each do |product| %>
    <%= product.lookupCode %>
    <%= button_to "Show", product_path(product.lookupCode), :method => "get" %>
<% end %>

app/views/products/show.html.erb
<%= button_to "Product Listing", products_path, method: :get %>
<br>
Lookup Code: <%= @product.lookupCode %>
<br>
Price: <%= @product.price %> 
<br>
Product Count: <%= @product.count %>
<br>
<%= button_to "Edit", edit_product_path(@product.lookupCode), method: :get %>